// Generated by BUCKLESCRIPT VERSION 1.7.1, PLEASE EDIT WITH CARE
'use strict';

import * as $$String from "bs-platform/lib/es6/string.js";

function titleCase(sentence) {
  return sentence.split((/\s+/)).map($$String.capitalize).join();
}

export {
  titleCase ,
  
}
/* No side effect */
