// Generated by BUCKLESCRIPT VERSION 1.7.1, PLEASE EDIT WITH CARE
'use strict';

import * as $$String from "bs-platform/lib/es6/string.js";

function truncateString(str, n) {
  if (str.length > n) {
    return $$String.sub(str, 0, n) + "...";
  } else {
    return str;
  }
}

export {
  truncateString ,
  
}
/* No side effect */
