// Generated by BUCKLESCRIPT VERSION 1.7.1, PLEASE EDIT WITH CARE
'use strict';

import * as List  from "bs-platform/lib/es6/list.js";
import * as Curry from "bs-platform/lib/es6/curry.js";

function nativeFind(list, pred) {
  return List.find(pred, list);
}

function recursiveFind(list, pred) {
  var _l = list;
  while(true) {
    var l = _l;
    if (l) {
      var tl = l[1];
      var hd = l[0];
      if (tl) {
        if (tl[1]) {
          _l = tl;
          continue ;
          
        } else if (Curry._1(pred, hd)) {
          return hd;
        } else {
          _l = tl;
          continue ;
          
        }
      } else {
        _l = tl;
        continue ;
        
      }
    } else {
      return /* false */0;
    }
  };
}

export {
  nativeFind    ,
  recursiveFind ,
  
}
/* No side effect */
