// Generated by BUCKLESCRIPT VERSION 1.7.1, PLEASE EDIT WITH CARE
'use strict';

import * as List       from "bs-platform/lib/es6/list.js";
import * as Pervasives from "bs-platform/lib/es6/pervasives.js";

function maxOfList(list) {
  return List.fold_left(Pervasives.max, 0, list);
}

function largestOfEach() {
  return function (param) {
    return List.map(maxOfList, param);
  };
}

export {
  maxOfList     ,
  largestOfEach ,
  
}
/* No side effect */
