// Generated by BUCKLESCRIPT VERSION 1.7.1, PLEASE EDIT WITH CARE
'use strict';

import * as $$String    from "bs-platform/lib/es6/string.js";
import * as Caml_string from "bs-platform/lib/es6/caml_string.js";

function reverseString(str) {
  var lastIndex = str.length - 1 | 0;
  return $$String.mapi(function (i, _) {
              return Caml_string.get(str, lastIndex - i | 0);
            }, str);
}

export {
  reverseString ,
  
}
/* No side effect */
