// Generated by BUCKLESCRIPT VERSION 1.7.1, PLEASE EDIT WITH CARE
'use strict';


function convertCtoF(c) {
  return c * 1.8 + 32;
}

function convertFtoC(f) {
  return (f - 32) / 1.8;
}

export {
  convertCtoF ,
  convertFtoC ,
  
}
/* No side effect */
