// Generated by BUCKLESCRIPT VERSION 1.7.1, PLEASE EDIT WITH CARE
'use strict';

import * as $$String from "bs-platform/lib/es6/string.js";

function confirmEnding(str, target) {
  var targetIndex = str.length - target.length | 0;
  return +(target === $$String.sub(str, targetIndex, target.length));
}

export {
  confirmEnding ,
  
}
/* No side effect */
