// Generated by BUCKLESCRIPT VERSION 1.7.1, PLEASE EDIT WITH CARE
'use strict';

import * as Curry          from "bs-platform/lib/es6/curry.js";
import * as CamlinternalOO from "bs-platform/lib/es6/camlinternalOO.js";

var class_tables = [
  0,
  0,
  0
];

function findLongestWordLength() {
  if (!class_tables[0]) {
    var $$class = CamlinternalOO.create_table(0);
    var env_init = function () {
      return CamlinternalOO.create_object_opt(0, $$class);
    };
    CamlinternalOO.init_class($$class);
    class_tables[0] = env_init;
  }
  return Curry._1(class_tables[0], 0);
}

export {
  findLongestWordLength ,
  
}
/* No side effect */
