// Generated by BUCKLESCRIPT VERSION 1.7.1, PLEASE EDIT WITH CARE
'use strict';


function sumFibs(n) {
  var _prev = 0;
  var _curr = 1;
  var _acc = 0;
  while(true) {
    var acc = _acc;
    var curr = _curr;
    var prev = _prev;
    if (curr <= n) {
      var match = +(curr % 2 !== 0);
      _acc = match !== 0 ? acc + curr | 0 : acc;
      _curr = curr + prev | 0;
      _prev = curr;
      continue ;
      
    } else {
      return acc;
    }
  };
}

exports.sumFibs = sumFibs;
/* No side effect */
