// Generated by BUCKLESCRIPT VERSION 1.7.1, PLEASE EDIT WITH CARE
'use strict';

var $$String = require("bs-platform/lib/js/string.js");

function confirmEnding(str, target) {
  var targetIndex = str.length - target.length | 0;
  return +(target === $$String.sub(str, targetIndex, target.length));
}

exports.confirmEnding = confirmEnding;
/* No side effect */
