// Generated by BUCKLESCRIPT VERSION 1.7.1, PLEASE EDIT WITH CARE
'use strict';

var $$String = require("bs-platform/lib/js/string.js");

function truncateString(str, n) {
  if (str.length > n) {
    return $$String.sub(str, 0, n) + "...";
  } else {
    return str;
  }
}

exports.truncateString = truncateString;
/* No side effect */
