// Generated by BUCKLESCRIPT VERSION 1.7.1, PLEASE EDIT WITH CARE
'use strict';


function recursiveRepeatString(str, n) {
  var _n = n;
  var _acc = "";
  while(true) {
    var acc = _acc;
    var n$1 = _n;
    if (n$1 < 1) {
      return acc;
    } else {
      _acc = acc + str;
      _n = n$1 - 1 | 0;
      continue ;
      
    }
  };
}

function imperativeRepeatString(str, n) {
  var acc = "";
  var i = n;
  while(i > 0) {
    acc = acc + str;
    i = i - 1 | 0;
  };
  return acc;
}

exports.recursiveRepeatString  = recursiveRepeatString;
exports.imperativeRepeatString = imperativeRepeatString;
/* No side effect */
