// Generated by BUCKLESCRIPT VERSION 1.7.1, PLEASE EDIT WITH CARE
'use strict';

import * as React      from "react";
import * as ReactDOMRe from "reason-react/lib/es6/src/reactDOMRe.js";

ReactDOMRe.renderToElementWithId(React.createElement("h1", undefined, "Hello, world!"), "root");

export {
  
}
/*  Not a pure module */
