// Generated by BUCKLESCRIPT VERSION 1.7.1, PLEASE EDIT WITH CARE
'use strict';

var Caml_int32 = require("bs-platform/lib/js/caml_int32.js");

function sumRangeInclusive(min, max) {
  return (Caml_int32.imul(max, max + 1 | 0) / 2 | 0) - (Caml_int32.imul(min - 1 | 0, min) / 2 | 0) | 0;
}

exports.sumRangeInclusive = sumRangeInclusive;
/* No side effect */
