// Generated by BUCKLESCRIPT VERSION 1.7.1, PLEASE EDIT WITH CARE
'use strict';


function isBoolean(value) {
  var match = +(value === /* true */1 || value === /* false */0);
  if (match !== 0) {
    return /* true */1;
  } else {
    return /* false */0;
  }
}

exports.isBoolean = isBoolean;
/* No side effect */
