// Generated by BUCKLESCRIPT VERSION 1.7.1, PLEASE EDIT WITH CARE
'use strict';

var $$String    = require("bs-platform/lib/js/string.js");
var Caml_string = require("bs-platform/lib/js/caml_string.js");

function reverseString(str) {
  var lastIndex = str.length - 1 | 0;
  return $$String.mapi(function (i, _) {
              return Caml_string.get(str, lastIndex - i | 0);
            }, str);
}

exports.reverseString = reverseString;
/* No side effect */
