// Generated by BUCKLESCRIPT VERSION 1.7.1, PLEASE EDIT WITH CARE
'use strict';

var List       = require("bs-platform/lib/js/list.js");
var Pervasives = require("bs-platform/lib/js/pervasives.js");

function maxOfList(list) {
  return List.fold_left(Pervasives.max, 0, list);
}

function largestOfEach() {
  return function (param) {
    return List.map(maxOfList, param);
  };
}

exports.maxOfList     = maxOfList;
exports.largestOfEach = largestOfEach;
/* No side effect */
