// Generated by BUCKLESCRIPT VERSION 1.7.1, PLEASE EDIT WITH CARE
'use strict';

var List     = require("bs-platform/lib/js/list.js");
var Caml_obj = require("bs-platform/lib/js/caml_obj.js");

function getIndexToInsert(list, n) {
  return List.length(List.filter(function (v) {
                    return Caml_obj.caml_lessthan(v, n);
                  })(list));
}

function recIndexToInsert(list, n) {
  var _l = list;
  var _counter = 0;
  while(true) {
    var counter = _counter;
    var l = _l;
    if (l) {
      var xs = l[1];
      if (Caml_obj.caml_lessthan(l[0], n)) {
        _counter = counter + 1 | 0;
        _l = xs;
        continue ;
        
      } else {
        _l = xs;
        continue ;
        
      }
    } else {
      return counter;
    }
  };
}

exports.getIndexToInsert = getIndexToInsert;
exports.recIndexToInsert = recIndexToInsert;
/* No side effect */
