// Generated by BUCKLESCRIPT VERSION 1.7.1, PLEASE EDIT WITH CARE
'use strict';

var $$String = require("bs-platform/lib/js/string.js");

function titleCase(sentence) {
  return sentence.split((/\s+/)).map($$String.capitalize).join();
}

exports.titleCase = titleCase;
/* No side effect */
